global:
  imagePullPolicy: IfNotPresent
  environment: staging

api:
  image: "neurosynth-api:latest"
  replicas: 2
  servicePort: 80
  containerPort: 8000

triton:
  image: "nvcr.io/nvidia/tritonserver:24.04-py3"
  replicas: 1

llm:
  image: "neurosynth-vllm:latest"
  replicas: 1

causal:
  image: "neurosynth-causal:latest"
  replicas: 1

redis:
  image: redis:7
  size: 20Gi

ingress:
  enabled: true
  className: alb
  host: neurosynth.internal
  scheme: internal
  wafAclArn: ""

serviceAccount:
  irsaRoleArn: ""

secrets:
  managerPath: /neurosynth/prod

gpuResources:
  requests:
    nvidia.com/gpu: "2"
    memory: "60Gi"
    cpu: "8"
  limits:
    nvidia.com/gpu: "2"
    memory: "64Gi"
